### ISSUE TITLE
配合MySQL8使用会出错

### ISSUE THREAD

**Issue by lnnt** [wudaoren/miniBlog#2]
提示“数据库链接失败：this authentication plugin is not supported”，
是mysql驱动过旧的问题。

**Comment by stepbystep2** [comment]
更新驱动后，博客运行成功，但是功能逻辑出了问题，不知道是什么原因。

**Comment by wudaoren** [comment]
逻辑问题指的是什么？

**Comment by wudaoren** [comment]
> 更新驱动后，博客运行成功，但是功能逻辑出了问题，不知道是什么原因。

逻辑问题指的是什么？

**Comment by wudaoren** [comment]
> 更新驱动后，博客运行成功，但是功能逻辑出了问题，不知道是什么原因。

什么问题？

**Comment by stepbystep2** [comment]
> > 更新驱动后，博客运行成功，但是功能逻辑出了问题，不知道是什么原因。
> 
> 什么问题？

应该和 MySQL 及驱动没关系的
https://wwa.lanzous.com/iQ7VZhcfxfc
